application: cs2102-booking-system
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: main.app
  login: admin

- url: .*
  script: main.app

